# Generated by Django 4.2.6 on 2023-11-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream_truck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditemtype',
            name='has_flavor',
            field=models.BooleanField(default=False),
        ),
    ]
